src/GctgsWeb/Controllers/BoardGamesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using GctgsWeb.Models;
using GctgsWeb.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;

namespace GctgsWeb.Controllers
{
    [Authorize("RegisteredUser")]
    public class BoardGamesController : Controller
    {
        private readonly GctgsContext _context;
        private readonly EmailSettings _emailSettings;
        private readonly FirebaseSettings _firebaseSettings;

        public BoardGamesController(GctgsContext context, IOptions<EmailSettings> emailSettings, IOptions<FirebaseSettings> firebaseSettings)
        {
            _context = context;
            _emailSettings = emailSettings.Value;
            _firebaseSettings = firebaseSettings.Value;
        }

        public IActionResult Index()
        {
            return View(_context.BoardGames
                .Include(boardGame => boardGame.Owner)
                .OrderBy(boardGame => boardGame.Name)
                .ToList());
        }

        [HttpGet("boardgames/{id}")]
        public IActionResult BoardGame(int id)
        {
            var result = _context.BoardGames
                .Where(boardGame => boardGame.Id == id)
                .Include(boardGame => boardGame.Owner)
                .SingleOrDefault();

            if (result == null) return new NotFoundResult();

            if (_context.IsAdmin(User))
            {
                ViewBag.Admin = true;
                return View("Edit", result);
            }
            if (User.Identity.Name == result.Owner.Crsid)
            {
                ViewBag.Admin = false;
                return View("Edit", result);
            }
            return View(result);
        }

        [HttpGet("boardgames/locations/{location}")]
        public IActionResult Locations(string location)
        {
            return View("Index", _context.BoardGames
                .Include(boardGame => boardGame.Owner)
                .Where(boardGame => boardGame.Location == location)
                .OrderBy(boardGame => boardGame.Name)
                .ToList());
        }

        [HttpGet("boardgames/owners/{owner}")]
        public IActionResult Owners(string owner)
        {
            return View("Index", _context.BoardGames
                .Include(boardGame => boardGame.Owner)
                .Where(boardGame => boardGame.Owner.Crsid == owner)
                .OrderBy(boardGame => boardGame.Name)
                .ToList());
        }

        [HttpGet("boardgames/create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("boardgames/create")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BoardGame boardGame)
        {
            boardGame.Owner = _context.Users.Single(u => u.Crsid == User.Identity.Name);

            if (ModelState.IsValid)
            {
                _context.BoardGames.Add(boardGame);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(boardGame);
        }

        [HttpPost("boardgames/{id}")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, BoardGame updatedBoardGame)
        {
            if (ModelState.IsValid)
            {
                var result = _context.BoardGames
                    .Where(boardGame => boardGame.Id == id)
                    .Include(boardGame => boardGame.Owner)
                    .SingleOrDefault();

                if ((result.Owner.Crsid != User.Identity.Name) &&
                    !_context.IsAdmin(User))
                    return Unauthorized();

                if (_context.IsAdmin(User)) result.Name = updatedBoardGame.Name;
                result.Location = updatedBoardGame.Location;
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(updatedBoardGame);
        }

        [HttpPost("boardgames/delete/{id}")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var result = _context.BoardGames
                .Where(boardGame => boardGame.Id == id)
                .Include(boardGame => boardGame.Owner)
                .SingleOrDefault();

            if ((result.Owner.Crsid != User.Identity.Name) &&
                !_context.IsAdmin(User))
                return Unauthorized();

            _context.BoardGames.Remove(result);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost("boardgames/request/{id}")]
        public async Task<IActionResult> RequestBoardGame(int id)
        {
            var result = _context.BoardGames
                .Where(boardGame => boardGame.Id == id)
                .Include(boardGame => boardGame.Owner)
                .SingleOrDefault();

            var requester = _context.Users.Single(user => user.Crsid == User.Identity.Name);

            var request = new Request
            {
                DateTime = DateTime.Now,
                Requester = requester,
                BoardGame = result
            };

            var emailClient = new MailgunClient(_emailSettings);
            await emailClient.SendNotificationEmail(result.Owner.Email, result.Owner.Name, requester.Name, result.Name);

            if (result.Owner.FcmToken != null)
            {
                var firebaseClient = new FirebaseClient(_firebaseSettings);
                await firebaseClient.SendRequestNotification(result.Owner.FcmToken, requester, result);
            }

            _context.Requests.Add(request);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/GctgsWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GctgsWeb</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <a asp-area="" asp-controller="BoardGames" asp-action="Index" class="navbar-brand"><img src="/images/logo_small.png" class="pull-left" style="max-height:100%;" />GCTGS</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="BoardGames" asp-action="Index">Board Games</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="Index">Admin</a></li>
                </ul>
                <p class="nav navbar-text navbar-right">Hello, @User.Identity.Name!</p>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div id="notifications"></div>
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; 2016 - GCTGS</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>